### ISSUE TITLE
Can a big int grow if needed?

### ISSUE THREAD

**Issue by SuperFola** [stevenBorisko/BigInteger#1]
Hi, I didn't find anything in the code answering my question: when adding 2 big integers for example, if there is an overflow, can it expand its storage if needed (as python integers would do) to use the less possible storage for each big integer?
Thanks for your project, it is really helpful 😄

**Comment by stevenBorisko** [comment]
@SuperFola Hi! The width of a BigInteger will not be changed by any BigInteger member functions; however, you may manually change it with the function `resize`. Though this can get cumbersome to deal with, I think that the performance gained from static size is worth it.

Thanks for the feedback, glad you like it!
